### ISSUE TITLE
escape instead of stripping tags?

### ISSUE THREAD

**Issue by Fedcomp** [rgrove/sanitize#139]
is there a way to escape tags instead of stripping them? so if some tag hit blacklist it gets escaped,  for example:

&lt;span&gt; is replaced  with &amp;lt;span&amp;gt;

if there's such functionality in gem it's not in documentation, and i cant find it. if there's no such functionality, could you add it?

**Comment by rgrove** [comment]
Sorry, Sanitize doesn't currently support this because it's a lot more complicated than it seems. Way back in issue #1, I explained why this is tricky and why the results are often not what people expect. Issues #33 and #45 provide more detail.

In short, this is a feature people often think they want until they realize its shortcomings, and then they don't like it very much, so I've decided not to implement it in Sanitize.

That said, if you (or someone else) wanted this enough, you could write a [Transformer](https://github.com/rgrove/sanitize#transformers) to do it. I wish you luck. :smile:
