### ISSUE TITLE
extra spaces with mutliple html elements

### ISSUE THREAD

**Issue by herberzt** [rgrove/sanitize#140]
I have a string:
    `description = <p><div><div><a href="http://www.amazon.com">amazon</a></div></div></p>`

I have a function that does the following:
    `Sanitize.fragment(description)`

What I am expecting to be returned is "amazon" what i get is "   amazon   ". Is there anyway to prevent this by using a configuration?

**Comment by herberzt** [comment]
for now i have added .strip to the end to take care of the leading and trailing whitespace

**Comment by rgrove** [comment]
Yep! See the [:whitespace_elements](https://github.com/rgrove/sanitize#whitespace_elements-hash) config hash.

By default, Sanitize replaces certain elements (including `<p>`) with whitespace when they're removed, so that something like "foo<p>bar" will become "foo bar" (which is what most people expect) and not "foobar". But you can override the list of elements that get replaced with whitespace.

You can see the default config [here](https://github.com/rgrove/sanitize/blob/65e95d69382b612788fa57967c3f7b778be5bc2f/lib/sanitize/config/default.rb#L78-L109).
