### ISSUE TITLE
The default configurations should remove content for <style>

### ISSUE THREAD

**Issue by lluchs** [rgrove/sanitize#144]
The default BASIC and RESTRICTED configurations both will remove inline <style> tags, but not the CSS contained within them. I'd argue that this is never the desired or expected behavior when using an HTML sanitizer. Removing content for <style> (and possibly also <script>?) should be the default for those configurations, or there should be at least a hint in the documentations that users will probably want to do this.

**Comment by lluchs** [comment]
GitHub seems to have some issues with the formatting. Here's what my comment is supposed to look like:
![selection_003](https://cloud.githubusercontent.com/assets/516527/12298622/6189202c-ba13-11e5-85b4-172a57171883.png)

**Comment by rgrove** [comment]
Thanks for the suggestion!

The reason Sanitize doesn't remove the contents of `<style>` and `<script>` elements by default is that people often make the same mistake you made in your original issue description: typing the name of an HTML tag for purposes of discussion, without realizing that the content will be parsed as an HTML subset and sanitized.

In fact, GitHub actually uses Sanitize to sanitize issue descriptions and comments, and it's only the fact that Sanitize preserved the contents of your accidental `<style>` element that kept your issue description mostly readable. Ironic! :smile: 

That said, people use Sanitize for a variety of use cases, and I certainly understand why you might want to remove the contents of `<script>` and `<style>` tags for your particular use case. You can do this by creating a custom config like this:

```ruby
config = Sanitize::Config.merge(Sanitize::Config::BASIC,
  remove_contents: %w[script style]
)
```

If you (or someone else) would like to open a PR adding that info to the readme, I'd be happy to merge it! Otherwise I'll get to it when I have a moment.

**Comment by lluchs** [comment]
I'm not quite convinced. There are two use cases here:

1. Users type HTML (or Markdown) directly, as in GitHub. I agree that in this case, it's useful to keep the contents of these elements. However, if the user types `<style>`and wants to keep the content, they probably want to keep the tag itself as well. In fact, my text above would have appeared mostly fine if the tag wouldn't have been removed.

2. HTML is generated by another application (for example an email client). In this case, the user never knows that `<style>` elements are included and definitely doesn't want either the tag or the content to appear. If the user types `<style>`, the application will escape the brackets automatically.

I just don't see the third use case where you don't want the tag to appear, but only its content.

I see that sanitize is a pretty stable library at this point though, so if I'm the only one who is bothered by this, it's probably fine. ;)

**Comment by rgrove** [comment]
The only use case Sanitize _can_ fulfill is your nonexistent third use case. ;)

Use case 1 is impossible to fulfill, since it would require Sanitize to read the user's mind. There's no way to know whether the user wants the characters `<style>` to be represented literally (and thus escaped) or to open a style element (and thus parsed as HTML).

Use case 2 is fulfilled by simply escaping all HTML in user input, for which you don't need (and shouldn't use) Sanitize.

The use case for which Sanitize is actually intended is to allow users to use a safe subset of HTML, and to remove HTML that is not included in that subset while doing minimal damage to the remaining content. To accomplish this reliably, Sanitize _must_ parse input as HTML. If it encounters the characters `<style>`, then those characters must be treated as the opening tag of a style element.

There have been various attempts (by myself and others) over the years to achieve the mind-reading hybrid you described in use case 1 where Sanitize would encounter a `<style>` tag and escape it instead of removing it, but there are too many edge cases and ambiguities involved in that approach.

Instead, I've chosen to keep Sanitize's core functionality focused on a single use case: unsafe HTML goes in, safe HTML comes out. If you want to parse input using rules other than the HTML5 parsing algorithm, or if you want to serialize that HTML using different rules than Sanitize uses, you can either use your own pre-parsing step before passing content to Sanitize, or you can create custom Sanitize transformers that implement your desired behavior.
