### ISSUE TITLE
Sanitizer doesn't work for SVGs due to case-sensitive attributes

### ISSUE THREAD

**Issue by stanhu** [rgrove/sanitize#147]
According to https://www.w3.org/TR/SVG/styling.html#CaseSensitivity:

> Because presentation attributes are expressed as XML attributes, presentation attributes are case-sensitive and must match the exact name as specified...

The `downcase` call here forces the attributes (e.g. `viewBox`) to be matched and cleaned in lowercase form:

https://github.com/rgrove/sanitize/blob/master/lib/sanitize/transformers/clean_element.rb#L93

Until this is fixed, sanitizing SVG files will not work right.

**Comment by rgrove** [comment]
Before I respond, one caveat: Sanitize currently makes no effort to support SVGs, and I don't test SVG support or recommend using Sanitize for SVG markup, mainly because I've never had a need for it so I haven't given it any attention. In fact, as you can see in [this comparison chart](https://github.com/rgrove/sanitize/blob/a9ae46a/COMPARISON.md#feature-comparison), I've explicitly indicated that Sanitize does not support SVG.

That said, my understanding is that, when used within an HTML document, SVG elements are considered [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements). The [HTML syntax definition for attributes](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) says that all attribute names&mdash;including attributes on foreign elements used within HTML&mdash;are case-insensitive:

> In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of lower- and uppercase letters that are an ASCII case-insensitive match for the attribute's name.

On the other hand, when I actually _test_ this, it appears that in Chrome at least (I didn't try any other browsers), SVGs in HTML don't render correctly when I use arbitrary casing for attribute names. So either the HTML standard is overly optimistic or browsers don't adhere to the standard or I'm misinterpreting the standard.

In any case, fixing this would mean that Sanitize would have to have to treat attributes on SVG elements differently from attributes on HTML elements, which means Sanitize has to know which elements are SVG elements, which would complicate things a bit and increase the maintenance burden for functionality I don't personally need, which is why it hasn't happened.

**Comment by stanhu** [comment]
Right. I was looking at implementing a custom SVG whitelist, but then I ran into this issue. I then looked at adding custom transformer for SVG elements (essentially just removing the `downcase` in `CleanElement`), but it appears that the `CleanElement` transformer is [always used in the sanitizer](https://github.com/rgrove/sanitize/blob/master/lib/sanitize.rb#L99) so I can't get away with even doing this. 

Any suggestions on the best way to proceed? Would it make sense to be able to override the `transformers` config completely?

**Comment by rgrove** [comment]
A custom transformer is exactly what I would recommend. :smile: 

Your transformer can return a hash with a `:node_whitelist` key whose value is an Array or Set of nodes that `CleanElement` should ignore. So as long as your transformer is satisfied that an element is safe, you can include that element in `:node_whitelist` and Sanitize won't touch it.

Docs are [here](https://github.com/rgrove/sanitize#output), and the [YouTube video embed example](https://github.com/rgrove/sanitize#example-transformer-to-whitelist-youtube-video-embeds) demonstrates how node whitelisting works. Hope that helps!

**Comment by stanhu** [comment]
Thank you for your help! It turns out GitLab is stuck on sanitize 2.1.0 for now, and it looks like documents are parsed as HTML instead of XML. I'll use something else instead since I'm not sure I want to bring in Nokogumbo as another dependency.

**Comment by kivikakk** [comment]
Sorry to necro, but I found it was sufficient to use `Sanitize.new(config).clean!(input, Nokogiri::XML::DocumentFragment)` (on 2.0.x) and case was preserved correctly :+1:
