### ISSUE TITLE
Wrong checking for tags close?

### ISSUE THREAD

**Issue by shir** [rgrove/sanitize#148]
Here is html example:
```html
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:p="urn:schemas-microsoft-com:office:powerpoint" xmlns:a="urn:schemas-microsoft-com:office:access" xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882" xmlns:s="uuid:BDC6E3F0-6DA3-11d1-A2A3-00AA00C14882" xmlns:rs="urn:schemas-microsoft-com:rowset" xmlns:z="#RowsetSchema" xmlns:b="urn:schemas-microsoft-com:office:publisher" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:c="urn:schemas-microsoft-com:office:component:spreadsheet" xmlns:odc="urn:schemas-microsoft-com:office:odc" xmlns:oa="urn:schemas-microsoft-com:office:activation" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:q="http://schemas.xmlsoap.org/soap/envelope/" xmlns:rtc="http://microsoft.com/officenet/conferencing" xmlns:D="DAV:" xmlns:Repl="http://schemas.microsoft.com/repl/" xmlns:mt="http://schemas.microsoft.com/sharepoint/soap/meetings/" xmlns:x2="http://schemas.microsoft.com/office/excel/2003/xml" xmlns:ppda="http://www.passport.com/NameSpace.xsd" xmlns:ois="http://schemas.microsoft.com/sharepoint/soap/ois/" xmlns:dir="http://schemas.microsoft.com/sharepoint/soap/directory/" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:dsp="http://schemas.microsoft.com/sharepoint/dsp" xmlns:udc="http://schemas.microsoft.com/data/udc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sub="http://schemas.microsoft.com/sharepoint/soap/2002/1/alerts/" xmlns:ec="http://www.w3.org/2001/04/xmlenc#" xmlns:sp="http://schemas.microsoft.com/sharepoint/" xmlns:sps="http://schemas.microsoft.com/sharepoint/soap/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:udcs="http://schemas.microsoft.com/data/udc/soap" xmlns:udcxf="http://schemas.microsoft.com/data/udc/xmlfile" xmlns:udcp2p="http://schemas.microsoft.com/data/udc/parttopart" xmlns:st="" xmlns:st1="urn:schemas-microsoft-com:office:smarttags" xmlns="http://www.w3.org/TR/REC-html40"
xmlns:ns0="http://schemas.microsoft.com/office/2004/12/omml">
  <head>
    <o:SmartTagType namespaceuri="urn:schemas-microsoft-com:office:smarttags" name="City"/>
  </head>
  <body>
    <div>
      <p>Test text</p>
    </div>
  </body>
</html>
```
There is `o:SmartTagType`, which is closed with `/>` at the end. If I try to sanitize this html I will have next output:
```
"<html><body></body></html>\n"
```
If I remove `o:SmartTagType` then I get that I expected:
```
"<html>\n  <body>\n    <div>\n      <p>Test text</p>\n    </div>\n  \n\n</body></html>\n"
```
If I change tag closing to `</o:SmartTagType>`, then I get that I expected too:
```
"<html>\n  <body>\n    <div>\n      <p>Test text</p>\n    </div>\n  \n\n</body></html>\n"
```

As I know html/xml allow both types of tags close methods.

May be I may use some transformers to workaround this issue?

**Comment by rgrove** [comment]
What version of Sanitize are you using? What config are you using? Are you calling `Sanitize.document` or `Sanitize.fragment`?

Since you're passing in a complete document, I'll assume you're calling `Sanitize.document` with a config that whitelists `html`, `body`, `div`, and `p`. Here's the output I get using Sanitize 4.0.1 and the input HTML you provided:

```html
<html>
      <body>


      <div>
        <p>Test text</p>
      </div>


</body></html>
```

If you're not seeing this, then my guess is you're not using a recent version of Sanitize.

**Comment by shir** [comment]
Was using 4.0.0 and just updated to 4.0.1 (nokogiri 1.6.7.2) but have same result:
```
pry(main)> Sanitize.document(File.read('test.html'), Sanitize::Config.merge(Sanitize::Config::RELAXED, remove_contents: true))
=> "<html><head>\n    </head><body></body></html>\n"
```
Content of `test.html` file is in first message.

Without `remove_contents: true` option, I got same result as you. But I want to remove it because in real case I have many other elements which should be removed. This is just extracted example of issue.

**Comment by rgrove** [comment]
Ah, that explains it.

Here's what the element tree looks like after your original HTML is parsed:

-   html
    -   head
    -   body
        -   o:smarttagtype
            -   div
                -   p

In HTML, the [`head` element](https://html.spec.whatwg.org/multipage/semantics.html#the-head-element) is only allowed to contain [metadata content](https://html.spec.whatwg.org/multipage/dom.html#metadata-content-2). Since `o` is not metadata content, it isn't allowed inside the `head` element's content, so the parser moves it into the body as the body's first child.

Additionally, since `o` is not an HTML [void element](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it isn't technically allowed to be self-closing. The parser thus ignores the `/>` and treats `<o:SmartTagType ... />` as an opening tag without a matching closing tag, meaning that it consumes everything that follows it until the `</body>` tag, so the `div` and `p` elements become descendants of `o`.

And since you're using `remove_contents: true` and the `o` element is not in your whitelist, Sanitize removes it along with its contents, which includes the `div` and the `p` elements.

Sanitize's parser is doing exactly what the spec says it should here, and Sanitize is also cleaning up the node tree exactly as your config says it should, so there's no bug here. If you want Sanitize to remove the contents of all elements _except_ `o`, then a custom transformer would be the best solution.

Hope this helps!

**Comment by shir** [comment]
@rgrove
Not sure if this is right solution:

> Additionally, since `o` is not an HTML void element, it isn't technically allowed to be self-closing.

because looks like in [link you have provided](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) this element should be interpretated as foreign element and there is next:

> Foreign elements must either have a start tag and an end tag, or a **start tag that is marked as self-closing**, in which case they must not have an end tag.

In any case. Could you provide example of transformer to emulate `remove_content: false` for single element?

**Comment by rgrove** [comment]
> ...this element should be interpretated as foreign element...

A "foreign element" is [an element from the MathML or SVG namespace](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), not just any element that isn't defined in the HTML standard.

> In any case. Could you provide example of transformer to emulate remove_content: false for single element?

Sorry, I don't have time to write custom transformers for people. Please read [the documentation](https://github.com/rgrove/sanitize#transformers), look at the existing examples, and give it your best shot.
