### ISSUE TITLE
Weakness in CSS standalone sanitizer

### ISSUE THREAD

**Issue by tim-friedrich** [rgrove/sanitize#150]
hey,

I think we found a weakness in the css standalone sanitizer. 
We have a field where users can write css which is included with a style tag afterwards. 
The input is sanitized with Sanitize::CSS.stylesheet(css, Sanitize::Config::RELAXED).

if you enter:
```
div[id="main</style><script>alert("hi")</script><style>"]{
  display:block;
}
```

Then the script and style tags are not sanitized. So the javascript is executed.

**Comment by rgrove** [comment]
I understand why this could be confusing, but to be clear: this isn't a bug or a weakness in Sanitize's CSS sanitizer. The reason this happens is that a standalone CSS stylesheet and CSS within a `<style>` tag are two different contexts, with different parsing rules.

The CSS you posted is safe within the context of a standalone stylesheet (i.e., an external CSS file loaded via `<link>`), which is how you've told Sanitize to treat it. However, it's not safe within the context of a `<style>` element in HTML, because the contents of a `<style>` element must follow HTML's parsing rules.

This is why Sanitize's readme has two sections describing how to sanitize CSS: [CSS in HTML](https://github.com/rgrove/sanitize#css-in-html) and [Standalone CSS](https://github.com/rgrove/sanitize#standalone-css). Please let me know if you think these sections could be improved.

Here's how you would sanitize your input as CSS-in-HTML:

```ruby
input = %[
  <style>
  div[id="main</style><script>alert("hi")</script><style>"]{
    display:block;
  }
  </style>
]

html = Sanitize.fragment(input, Sanitize::Config::RELAXED)
```

This produces the following sanitized output:

```

  alert("hi")
```

If you wanted to avoid leaving the sanitized contents of the unsafe elements behind, you could enable the `:remove_contents` option:

```ruby
Sanitize.fragment(input, Sanitize::Config.merge(
  Sanitize::Config::RELAXED, :remove_contents => true
))
```

Hope this helps!

**Comment by tim-friedrich** [comment]
Thank you for you response. 
I missed the point that the Sanitize::CSS.stylesheet is for external documents only. 
I already changed it to the fragment sanitizer. But actually this also sanitize for e.g. direct inheritanze(body > div). I had a look at your documentation but couldnt figure out how to whitelist this. Any ideas?

**Comment by rgrove** [comment]
> I already changed it to the fragment sanitizer. But actually this also sanitize for e.g. direct inheritanze(body > div).

Sorry, I don't understand the problem. Can you please share the code you're using to call Sanitize, the input you're providing, and what output you expect?
