### ISSUE TITLE
More detailed @import parsing

### ISSUE THREAD

**Issue by nikz** [rgrove/sanitize#151]
Hiya @rgrove!

First off, thanks for the awesome gem 😄 

We're using something like the below monkey patch to allow our users to `@import` Google Fonts without also allowing generic `@import 'whatever`;

Would you be interested in me working this into a proper PR (potentially with better named config options etc!), or even extending the `transformer` functionality to allow passing in blocks for the CSS node parsing also?

Happy to do so, or if it's not something you want, that's cool too.

Thanks again! 

Nik

⚠️ HORRIBLE MONKEYPATCH FOLLOWS ⚠️ 
--

```ruby
class Sanitize::CSS

  protected

    def at_rule_with_import_url_checking!(rule)
      name = rule[:name].downcase

      if name == "import"
        url_token = rule[:tokens].detect { |t| t[:node] == :url }
        return nil unless url_token

        import_url = url_token[:value] || ""
        starts_with_allowed_location = Array.wrap(config[:allowed_at_import_locations]).detect do |prefix|
          import_url.starts_with?(prefix)
        end
        return nil unless starts_with_allowed_location
      end

      at_rule_without_import_url_checking!(rule)
    end

    alias_method_chain :at_rule!, :import_url_checking

end
```

**Comment by rgrove** [comment]
> We're using something like the below monkey patch to allow our users to `@import` Google Fonts without also allowing generic `@import 'whatever`;

Great idea! This makes a lot of sense.

> Would you be interested in me working this into a proper PR (potentially with better named config options etc!), or even extending the transformer functionality to allow passing in blocks for the CSS node parsing also?

Thanks for asking! I'd definitely be interested in a PR that adds a config option for whitelisting `@import` URLs. It might even allow you to specify a block that should be called to validate the URL.

I don't think we should go as far as building full CSS transformer functionality though. That'd be complicated, since it's a lot trickier to transform the CSS parse tree safely than it is to transform an HTML DOM. I also don't think it's something there's a lot of demand for; there are better tools for arbitrarily transforming CSS.

**Comment by nikz** [comment]
@rgrove have added a PR for you to check out in #153
