### ISSUE TITLE
Sanitize.clean(nil) returns empty string ""

### ISSUE THREAD

**Issue by adomokos** [rgrove/sanitize#158]
We found a bug in our app today that originated from Sanitize.

I expected `Sanitize.clean(nil)` to return `nil`, but it returned empty string.
It originated back to [this line](https://github.com/rgrove/sanitize/blob/master/lib/sanitize.rb#L108).

Is that expected behavior? If I pass a value to a routine, and it has nothing to do with it, I would expect the original value returned to me unaltered. Am I missing something here?

**Comment by rgrove** [comment]
I'm sorry this caused a problem for you, but it is expected.

As indicated in the documentation, Sanitize's `document` and `fragment` methods accept HTML and return HTML.

`nil` isn't HTML, so Sanitize won't return it. But people sometimes pass `nil` to these methods even though they shouldn't. This isn't ideal, but it's understandable because people often use Sanitize to process user input and sometimes a value ends up being `nil` if the user didn't provide it.

When this happens, Sanitize returns an empty string because that's valid and safe HTML, which is what you should expect to get from Sanitize by default. Since `nil` isn't HTML, you shouldn't expect to get it from Sanitize.
