### ISSUE TITLE
Fails to strip out tags

### ISSUE THREAD

**Issue by bfad** [rgrove/sanitize#160]
It's possible with certain malicious payloads to prevent tags from being properly stripped.

Example:
```ruby
html = %q['">><marquee><img src=x onerror=confirm(1)></marquee>"></plaintext\></|\><plaintext/onmouseover=prompt(2)>
<script>prompt(3)</script><isindex formaction=javascript:alert(4) type=submit>'-->"></script>
<script>alert(5)</script>">
<img/id="confirm&lpar;1)"/alt="/"src="/"onerror=eval(id)>'">]

Sanitize.fragment(html)
```

Expected:
```ruby
"'\"&gt;&gt;\"&gt;|\\&gt;\nprompt(3)'--&gt;\"&gt;\nalert(5)\"&gt;\n'\"&gt;"
```

Result:
```ruby
"'\"&gt;&gt;\"&gt;\n&lt;script&gt;prompt(3)&lt;/script&gt;&lt;isindex formaction=javascript:alert(4) type=submit&gt;'--&gt;\"&gt;&lt;/script&gt;\n&lt;script&gt;alert(5)&lt;/script&gt;\"&gt;\n&lt;img/id=\"confirm&amp;lpar;1)\"/alt=\"/\"src=\"/\"onerror=eval(id)&gt;'\"&gt;"
```

**Comment by rgrove** [comment]
Sanitize is behaving correctly here.

The opening [`<plaintext>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/plaintext) tag begins a [parser state](https://html.spec.whatwg.org/multipage/syntax.html#plaintext-state) in which everything that follows, all the way to the end of the file, is considered plain text, not HTML. To the parser, the "tags" that follow `<plaintext>` are not tags, they're just text content of the `<plaintext>` element. 

When Sanitize removes the `<plaintext>` element, it properly and safely escapes its content as if it is intended to be rendered as plain text. The default config specifies that the contents of removed elements should be preserved when it's safe to do so, and this is what Sanitize did.

If you'd like Sanitize to remove the contents of `<plaintext>` elements, you can use the [`:remove_contents`](https://github.com/rgrove/sanitize#remove_contents-boolean-or-array-or-set) config option:

```ruby
Sanitize.fragment(html, :remove_contents => ['plaintext'])
# => "'\"&gt;&gt;\"&gt;"
```

**Comment by bfad** [comment]
Your link to the tag mentions that `<plaintext>` has been deprecated since HTML 2 and obsoleted in HTML 5. So while this may not be a bug, can we turn it into a feature request? Could `Sanitize.fragment` have a flag for supporting earlier versions of HTML, but default to HTML 5?

**Comment by rgrove** [comment]
While `<plaintext>` is obsolete, a conforming HTML5 parser must still parse it (see the [parsing rules for the "in body" insertion mode](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody)).

This is necessary in order to ensure backward compatibility; if an HTML5 parser didn't parse everything after a `<plaintext>` tag as plain text, then pages that were originally written for HTML <=2 would suddenly be broken (and could possibly execute malicious HTML) in HTML5 browsers.

In any case, I'm afraid it wouldn't be feasible for Sanitize to provide alternative HTML parsers. Sanitize's implementation relies on specific parsing behaviors, so the subtle differences between parsers would also require subtle changes to how parsed nodes are sanitized. Since Sanitize's primary purpose is to produce HTML that can be safely rendered by browsers and since all modern browsers use HTML5-compliant (or nearly compliant) parsers, I don't think supporting alternative parsers would be a useful time investment.

**Comment by bfad** [comment]
I see now. Thanks for taking the time to explain.
