### ISSUE TITLE
SVG support in relaxed config

### ISSUE THREAD

**Issue by gfx** [rgrove/sanitize#162]
Are there plans to support SVG elements? They are just images that are safe to embed.

Can I make a pull-request for it?

**Comment by rgrove** [comment]
Thanks for asking. I don't plan to add SVG support to Sanitize, and I'm not currently interested in pull requests related to SVG support.

The reason is that SVG introduces new parsing behavior and a variety of new attack surfaces. Supporting it safely and correctly would take a lot of time and effort, and unfortunately I don't have the time or desire to implement or maintain this functionality in Sanitize.
