### ISSUE TITLE
Support for non-standard elements

### ISSUE THREAD

**Issue by steobrien** [rgrove/sanitize#165]
I notice that configurations including `Sanitize::Config::RELAXED` all strip obsolete-but-still-unfortunately-used tags like `<center>` and `<font>`.

In some use cases, for example email template rendering, many such tags remain commonly used and supported by browsers today. I found it mildly surprising that sanitize stripped these even in its most permissible configuration.

Could `Sanitize::Config::RELAXED` be extended to include [such elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Obsolete_and_deprecated_elements)? If so, I'd be happy to prepare a PR. If you think it's not a good idea, I'll go ahead and craft a local solution instead.

Thanks for maintaining this wonderful tool!

**Comment by rgrove** [comment]
Thanks for asking!

I think I'd prefer to keep the built-in configs focused on non-deprecated elements, since I think people generally assume that what comes out of Sanitize will be valid modern HTML. But you can create a custom config to add support for these elements locally, and could even distribute your config as a gem if you want to share it with others.

**Comment by steobrien** [comment]
Perfect. I've released and am using https://github.com/steobrien/sanitize_with_deprecated.
