### ISSUE TITLE
whitelist &nbsp;

### ISSUE THREAD

**Issue by washingon** [rgrove/sanitize#170]
unable to whitelist entity &nbsp;

**Comment by rgrove** [comment]
`&nbsp;` represents a character. You don't need to whitelist it. Sanitize will preserve the character in its output.

**Comment by washingon** [comment]
What am I doing wrong?

irb(main):001:0> require 'sanitize' => true irb(main):002:0> html="<h1>this is my test</h1>&nbsp;this is the line to test" => "<h1>this is my test</h1>&nbsp;this is the line to test" irb(main):003:0> Sanitize.fragment(html, Sanitize::Config::BASIC) => " this is my test \u00A0this is the line to test"

=> "<h1>this is my test</h1>&nbsp;this is the line to test" irb(main):007:0> Sanitize.fragment(html, Sanitize::Config::RELAXED) => "<h1>this is my test</h1>\u00A0this is the line to test"

**Comment by rgrove** [comment]
You're not doing anything wrong. Everything is working fine.

The HTML entity `&nbsp;` is equivalent to the Unicode "non-breaking space" character (`\u00A0`). Nokogiri, which Sanitize uses under the hood, doesn't distinguish between entities and the characters represented by entities, so when it stringifies the HTML, it outputs the character rather than the entity, because as far as it's concerned there's no difference between the two.

This behavior isn't something Sanitize has control over, but you don't need to worry about it. The resulting HTML still contains the non-breaking space character, and will still be rendered exactly the same by a browser.
