### ISSUE TITLE
Should strip non-space controls and noncharacters from input prior to parsing

### ISSUE THREAD

**Issue by cloudy9101** [rgrove/sanitize#179]
Hello, I think Sanitize#preprocesses not filter "\b" , then Nokogiri make it a �. Is it a mistake or a normal behavior?

**Comment by rgrove** [comment]
I'm not sure what character you mean by "\b". Can you please specify the actual hex value of the Unicode code point you're referring to?

In any event, if you're seeing a "�" somewhere, that's a good sign that either the input was not valid UTF-8 or the output is not being properly displayed or processed as UTF-8.

**Comment by rgrove** [comment]
Thanks for clarifying. I understand the problem now.

It looks like Sanitize should probably strip all non-space control characters and non-characters from the input prior to parsing, as described [in the HTML standard](https://html.spec.whatwg.org/multipage/parsing.html#preprocessing-the-input-stream). We currently strip some, but not all, of these characters, since we were following [older guidelines](https://www.w3.org/TR/unicode-xml/) that have since been withdrawn.

**Comment by ixti** [comment]
And now Sanitize do not strips out [U+2028](http://unicode.org/cldr/utility/character.jsp?a=2028) is that intentional?

**Comment by rgrove** [comment]
Yes. I'm not aware of any requirement in the HTML standard for parsers to strip U+2028. Have I missed something?

Previously Sanitize was stripping some characters that shouldn't have been stripped and was not stripping some characters that should have been stripped. Now it only strips characters that actually aren't allowed in HTML.

**Comment by ixti** [comment]
I'm not saying you've missed something. Was just double checking that it was intentional (before changing expectations in my app).
