### ISSUE TITLE
XHTML Output Option

### ISSUE THREAD

**Issue by siegfault** [rgrove/sanitize#186]
Hi! I recently worked on upgrading an app from `<3.0.0` to `4.6.4`. I was getting failures because we have instances that rely on `output: :xhtml`. I see that the output option was [removed](https://github.com/rgrove/sanitize/commit/037b44679008b5d2dec6b62e4020e3e13ac8b418) in 3.0.0 but wasn't able to find much context about why. XHTML's more strict closing tag requirements cause us to need the self-closing tag.

I am currently working around this by replacing something like
```ruby
Sanitize.fragment('<br />', elements: %w{br}, output: xhtml) # Output option ignored
=> "<br>"
```
with something like
```ruby
Sanitize.clean_node!(
  Nokogiri::HTML::DocumentFragment.parse('<br />'),
  elements: %w{br}
).to_xhtml
=> "<br />"
```
but was curious if there was an opportunity to introduce xhtml support back into sanitize. Is there any context I missed about why it was removed originally? I'd be happy to take a look at introducing a PR if desired. Either way, wanted to check the sanity of that work around. Thanks!

**Comment by rgrove** [comment]
Hi @siegfault. What's your use case for using XHTML as opposed to modern HTML?

Sanitize dropped support for XHTML output because it's not very useful and because it would have required a lot of effort to maintain support for both XHTML and modern HTML ("HTML5").

Browsers these days follow the HTML parsing rules defined by the living HTML standard, and most web developers are writing modern HTML rather than XHTML, so it was important to me that Sanitize both parse and produce HTML the way most people are using it (especially since even developers who use XHTML are almost never using strict XHTML).

Given the amount of work that would be involved in maintaining XHTML support (like adding an XHTML-specific test suite), I'm not sure it would be worthwhile.

**Comment by siegfault** [comment]
Thanks for the speedy response and backstory! That totally makes sense.

We're currently generating xml to be consumed by a PDF service. Some of the content displayed in the PDFs is user-generated in rich-content editors and so want to sanitize that content. Does that make sense?

I totally understand if this is not a typical use case of the gem. If so, I'd love confirmation that my work around doesn't seem totally insane 😄 

Thanks for the time!

**Comment by rgrove** [comment]
> We're currently generating xml to be consumed by a PDF service. Some of the content displayed in the PDFs is user-generated in rich-content editors and so want to sanitize that content. Does that make sense?

Got it. Not exactly the primary use case Sanitize targets, but totally valid.

> I totally understand if this is not a typical use case of the gem. If so, I'd love confirmation that my work around doesn't seem totally insane 😄

Yeah, for your use case I think your workaround is probably the best option. It bypasses the Gumbo parser and instead uses Nokogiri's libxml2-based parser, so it may not correctly parse all modern HTML, but as long as you're comfortable with that, it's fine.

Note that `Sanitize.clean_node!` is a deprecated name; the modern name for that method is `Sanitize.node!`. Think of it in a sentence: "Sanitize this node!" 😄
