### ISSUE TITLE
5.0.0: Sanitize.fragment does not remove HTML entities

### ISSUE THREAD

**Issue by agross** [rgrove/sanitize#193]
Sanitize 4.x removed the HTML entity from the string `foo&nbsp;bar` below (yielding `foo bar`). From the [changelog](https://github.com/rgrove/sanitize/blob/master/HISTORY.md) it's unclear why version 5 no longer does this. Any hints are greatly appreciated.

```rb
>> require 'sanitize'
true
>> Sanitize::VERSION
"5.0.0"
>> Sanitize.fragment('foo&nbsp;bar', Sanitize::Config::RELAXED)
"foo&nbsp;bar"
>> Sanitize.fragment('foo&nbsp;bar', Sanitize::Config::BASIC)
"foo&nbsp;bar"
>> Sanitize.fragment('foo&nbsp;bar', Sanitize::Config::RESTRICTED)
"foo&nbsp;bar"
```

**Comment by rgrove** [comment]
HTML serialization in Sanitize 4.x was performed by Nokogiri, so the output would depend more on the Nokogiri version than the Sanitize version. For instance, with Sanitize 4.6.6 and Nokogiri 1.10.0, I see the following:

```
irb(main):002:0> Sanitize::VERSION
=> "4.6.6"
irb(main):003:0> Sanitize.fragment('foo&nbsp;bar', Sanitize::Config::RELAXED)
=> "foo&nbsp;bar"
```

Sanitize 5.0 upgraded to [Nokogumbo 2.0](https://github.com/rubys/nokogumbo/blob/master/CHANGELOG.md#200---2018-10-04), which now performs its own spec-compliant HTML serialization rather than relying on Nokogiri's serializer. That could be another reason for differences in HTML output (this was mentioned in the changelog).

**Comment by agross** [comment]
I just did a test:

```rb
>> require 'sanitize'
true
>>  Sanitize::VERSION
"4.6.6"
>> Nokogiri::VERSION
"1.10.0"
>> Sanitize.fragment('foo&nbsp;bar', Sanitize::Config::RELAXED)
"foo\u00A0bar"
>> Sanitize.fragment('foo&nbsp;bar')
"foo\u00A0bar"
>> puts Sanitize.fragment('foo&nbsp;bar')
foo bar
```

Nokogiri 1.10 at least converts the entity to something space-like.

**Comment by rgrove** [comment]
Interesting. I'm not sure why we're seeing a difference while using the same version of Nokogiri. 

In any case, `\u00A0` is the [non-breaking space character](https://graphemica.com/00A0). It and `&nbsp;` should be indistinguishable in a UTF-8 HTML document, since they both result in the same character being rendered. Is this causing a problem for you?

**Comment by agross** [comment]
> Is this causing a problem for you?

Yes, I used cleaned-up strings in element IDs that should be stable.

I'm using this with a static site compiler:

* String in YAML frontmatter: `title: Some&nbsp;title`
* Code:
  ```rb
  require 'sanitize'
  require 'babosa'

  def cleaned_up(str)
    Sanitize.fragment(str).to_slug.normalize.to_s
  end
  ```
* HTML template: `<h1 id="<%= cleaned_up(title) %>"><%= title></h1>`

Yields `h1#some-title` (4.6.6) and `h1#somenbsptitle` (5.0.0).

**Comment by rgrove** [comment]
I'm sorry that your use case was affected, but please note that Sanitize has only ever been intended to output HTML or CSS. In HTML, the literal character `\u00A0` and the entity `&nbsp;` are functionally equivalent. Unfortunately, you were relying on incidental behavior that was not part of Sanitize's contract, since Sanitize produces HTML while your use case expects plain text and can't handle HTML entities.

Sanitize can still perform the HTML sanitization step for you, but you'll need to either use an additional tool or write some code to further transform the HTML Sanitize produces into plain text that's suitable for your needs. If you have Sanitize remove all HTML tags, then this may be as simple as writing a regex that removes entities or replaces them with acceptable replacement characters.

**Comment by agross** [comment]
OK, I obviously wasn't aware of that. The (deprecated) `Sanitize.clean` API suggested that Sanitize removes all HTML-related things from strings.

**Comment by agross** [comment]
Let me put that slightly differently: I was *under the impression* that it would remove/clean all HTML-related things.

**Comment by jalberto** [comment]
I was under the same impression as @agross and having similar troubles after the upgrade.
I understand this is a major version and get @rgrove explanation.

by the README: "...you can tell Sanitize to allow certain HTML elements, certain attributes within those elements..." should not `&nbsp` be considered an HTMl element hence possible to allow/disallow it?

**Comment by rgrove** [comment]
@jalberto I’m sorry you found this confusing, but entities aren’t elements. 

Sanitize doesn’t offer the ability to allow or disallow entities.

**Comment by jalberto** [comment]
thanks @rgrove good for me :)

Still wondering why this behaviour has changed, is related to nokogumbo or sanitize it self?

**Comment by rgrove** [comment]
> Still wondering why this behaviour has changed, is related to nokogumbo or sanitize it self?

Yes, it's related to Nokogumbo. I answered this here: https://github.com/rgrove/sanitize/issues/193#issuecomment-452783526
