### ISSUE TITLE
parser_options requires different formatting than other options

### ISSUE THREAD

**Issue by jakemmarsh** [rgrove/sanitize#195]
I'm on Sanitize `5.1.0`. Just updated to use the new `parser_options` (thanks for adding!)

My options were originally formatted like this:
```
remove_contents: ["script"],
      attributes: {
        "a" => ["class", "href", "rel", "title", "target"],
      },
      add_attributes: {
        "a" => { "target" => "_blank", "rel" => "noopener noreferrer" },
      },
      parser_options: {
        "max_tree_depth" => -1,
      },
```

However, this throws an error:

```
TypeError:
       hash key "max_tree_depth" is not a Symbol
     # ./app/services/gmail/gmail_message_metadata/u
```

So I thought no problem, I'll update the hash syntax for all of the options and be consistent.
```
remove_contents: ["script"],
      attributes: {
        a: ["class", "href", "rel", "title", "target"],
      },
      add_attributes: {
        a: { target: "_blank", rel: "noopener noreferrer" },
      },
      parser_options: {
        max_tree_depth: -1,
      },
```

This stopped blowing up, but also stopped applying any of the other options (`attributes`, `add_attributes`, or `remove_contents`).

It seems they currently just have conflicting expectations for the hash format.

**Comment by rgrove** [comment]
Sorry about the confusion here. I agree it's a little awkward. 

This is Sanitize's age showing. Sanitize predates the existence of Ruby's newer hash syntax, so the config format was designed with the old syntax in mind, in which it sometimes made sense for some keys to be symbols and others to be strings. In the new hash syntax, all keys must be symbols.

Nokogumbo expects all the keys in the `parser_options` hash to be symbols. Sanitize's config hash expects symbol keys for everything except HTML tag and attribute names, which must be strings since that's how they're represented in parser output.

For now, you'll need to use the old-style hashrocket syntax for Sanitize config hashes that need string keys.

If you don't mind mixing and matching, this will work:

```
remove_contents: ["script"],
      attributes: {
        "a" => ["class", "href", "rel", "title", "target"],
      },
      add_attributes: {
        "a" => { "target" => "_blank", "rel" => "noopener noreferrer" },
      },
      parser_options: {
        max_tree_depth: -1,
      },
```

But if you want consistency, you'll need to use the old-style syntax everywhere:

```
:remove_contents => ["script"],
      :attributes => {
        "a" => ["class", "href", "rel", "title", "target"],
      },
      :add_attributes => {
        "a" => { "target" => "_blank", "rel" => "noopener noreferrer" },
      },
      :parser_options => {
        :max_tree_depth => -1,
      },
```
