### ISSUE TITLE
Link tags need cleaned up after sanitizing

### ISSUE THREAD

**Issue by AustinWood** [rgrove/sanitize#220]
I expect no changes to my string other than removing unallowed tags and attributes, but the string looks wildly different after sanitizing, and I must reformat it so my site can render properly.

```
# Before sanitize
"\"<p>visit our <a href=\\\"www.mysite.com\\\" rel=\\\"noopener noreferrer\\\" target=\\\"_blank\\\">website</a></p>\""

# After sanitize
"\"<p>visit our <a href=\"\\%22www.mysite.com\\%22\" target=\"\\&quot;_blank\\&quot;\">website</a></p>\""

# CGI.unescapeHTML
"\"<p>visit our <a href=\"\\%22www.mysite.com\\%22\" target=\"\\\"_blank\\\"\">website</a></p>\""

# .gsub("\"\\%22", "\\\"").gsub("\\%22\"", "\\\"").gsub("\"\\\"", "\\\"").gsub("\\\"\"", "\\\"")
"\"<p>visit our <a href=\\\"www.mysite.com\\\" target=\\\"_blank\\\">website</a></p>\""
```

Ideally, I can sanitize and not need to call `CGI.unescapeHTML` or any `.gsub` to get the string back in the proper format. Is this a bug, or am I using the gem incorrectly?

**Comment by rgrove** [comment]
If I'm understanding correctly that your input is a string defined like this:

```ruby
input = "\"<p>visit our <a href=\\\"www.mysite.com\\\" rel=\\\"noopener noreferrer\\\" target=\\\"_blank\\\">website</a></p>\""
```

...then the actual HTML content of that string (after the escapes are parsed) is this:

```html
"<p>visit our <a href=\"www.mysite.com\" rel=\"noopener noreferrer\" target=\"_blank\">website</a></p>"
```

Note that the backslashes here are not escapes; they're literal backslash characters that exist in the HTML that enters the parser.

When Nokogiri parses this HTML, it sees `href=\"www.mysite.com\"`. Since the first non-whitespace character after the `=` is `\` and not `"`, the attribute's value is considered unquoted, resulting in the value `\"www.mysite.com\"`. The value of an `href` attribute [must be a valid URL](https://html.spec.whatwg.org/#links-created-by-a-and-area-elements), so the `"` is URI-encoded as `%22` in order to make the URL valid.

A similar thing happens with `target=\"_blank\"`: while the parser tolerates the existence of a literal `"` in the value of an unquoted attribute and recovers gracefully, [this is technically invalid HTML](https://html.spec.whatwg.org/#parse-error-unexpected-character-in-unquoted-attribute-value). In order to make it valid, the `"` is encoded as `&quot;`.

Despite having been given invalid input, Sanitize parses it correctly and returns safe and valid HTML, which is exactly what it's supposed to do, so there doesn't appear to be a bug here. Hope this helps!

**Comment by AustinWood** [comment]
Thank you so much for the detailed response. Huge help to understand what's going on!
